name: Test
on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: g++ main.cpp -o main
      - run: ./main
  test-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - run: clang++ main.cpp -o main
      - run: ./main