name: Test
on: [push]

jobs:
  test:
    stategy:
      matrix:
        os: [ubuntu-latest,macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: make
      - run: ./main