name: Test
on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: g++ main.cpp -o main
      - run: ./main
  test-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - run: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk main.cpp -o main 
      - run: ./main