name: Test
on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: g++ main.cpp -o main
      - run: ./main
  test-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - run: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_INT128 -DHAVE_INT64 -DHAVE_KHASHV -DNCPU=3 -D__STDC_FORMAT_MACROS  -march=native -DLTO -O3 -DNDEBUG -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -std=c++0x -o main.cpp.o -c main.cpp
      - run: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk main.cpp.o -o main
      - run: ./main